### ISSUE TITLE
Question: how do I configure the workflow to run on a specific branch?

### ISSUE THREAD

**Issue by egonw** [caltechlibrary/baler#4]
The context is the use here: https://github.com/egonw/cdkbook/blob/source/.github/workflows/baler.yml

Here, there are two branches used, one with the sources, another with the final markdown files for GitHub Pages hosting. I need to action to run on the second branch.

**Comment by mhucka** [comment]
Hi Egon - to configure a GitHub Actions workflow such that its trigger is restricted to a branch, you would add a [`branch:` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore). Depending on which branch is the one for GH pages (I see 3 branches in that repo – is it the `master` branch in your repo?), it would be something like this:

```yaml
on:
  schedule:  # Cron syntax is: "min hr day-of-month month day-of-week"
    - cron: 00 04 * * 1
  push:
    branches:
      - master
    paths: ['**.md']
  workflow_dispatch:
```

Change `master` if that's not the right branch name.

If you also want it to run on that branch using the schedule, then that's a little tricker. The `schedule` trigger [works only on the default or base branch](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule), so if the branch you want to run it on is the default branch, then all is fine, but if it's not the default branch, it's more complicated. I'm not sure it can be done without changing the Baler workflow definition to add a parameter for the branch. Let me know if we need to pursue that.
